# Save Model Using Joblib and Pickle

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn import linear_model


In [3]:
df = pd.read_csv("homeprices.csv")
df

area   price
0  2600  550000
1  3000  565000
2  3200  610000
3  3600  680000
4  4000  725000

In [4]:
new_df = df.drop('price',axis='columns')
new_df
price = df.price
price
reg = linear_model.LinearRegression()
reg.fit(new_df,price)


LinearRegression()

In [5]:
reg.coef_
reg.intercept_
135.78767123*3300+180616.43835616432

628715.7534151643

In [6]:
d =pd.read_csv("areas.csv")
d.head(5)

area
0  1000
1  1500
2  2300
3  3540
4  4120

In [7]:
p=reg.predict(d)

In [9]:
d['prices']=p
d.head(5)


area         prices
0  1000  316404.109589
1  1500  384297.945205
2  2300  492928.082192
3  3540  661304.794521
4  4120  740061.643836

In [10]:
d.to_csv("prediction.csv",index=False)

In [19]:
reg.predict([[5000]])

C:\ProgramData\anaconda3\Lib\site-packages\sklearn\base.py:464: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([859554.79452055])

# Pickle using

In [11]:
import pickle

In [13]:
with open('model_pickle','wb') as f:
    pickle.dump(reg,f)

In [14]:
with open('model_pickle','rb') as f:
    mp = pickle.load(f)

In [20]:
mp.predict([[5000]])

C:\ProgramData\anaconda3\Lib\site-packages\sklearn\base.py:464: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([859554.79452055])

# Joblib using

In [27]:
import joblib


In [26]:
from sklearn.externals import joblib

ImportError: cannot import name 'joblib' from 'sklearn.externals' (C:\ProgramData\anaconda3\Lib\site-packages\sklearn\externals\__init__.py)

In [28]:
joblib.dump(reg,'model_joblib')

['model_joblib']

In [29]:
mj = joblib.load('model_joblib')

In [31]:
mj.predict([[5000]])

C:\ProgramData\anaconda3\Lib\site-packages\sklearn\base.py:464: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([859554.79452055])

In [32]:
mj.coef_

array([135.78767123])

In [33]:
mj.intercept_

180616.43835616432